"""initial schema

Revision ID: 1b194cbf3fde
Revises: 
Create Date: 2026-07-25 02:13:43.052205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b194cbf3fde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('taxonomy_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_category_name'), 'book_category', ['name'], unique=True)
    op.create_table('canonical_author',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('death_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nationality', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_author_source'), 'canonical_author', ['source'], unique=False)
    op.create_index(op.f('ix_canonical_author_source_id'), 'canonical_author', ['source_id'], unique=False)
    op.create_table('canonical_book',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('subtitle', sa.String(length=512), nullable=True),
    sa.Column('original_title', sa.String(length=512), nullable=True),
    sa.Column('edition', sa.String(length=255), server_default='', nullable=False),
    sa.Column('edition_number', sa.Integer(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('original_publication_year', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('series_number', sa.Float(), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('classification_type', sa.String(length=50), server_default='fiction', nullable=False),
    sa.Column('audience', sa.String(length=128), nullable=True),
    sa.Column('age_rating', sa.String(length=32), nullable=True),
    sa.Column('reading_level', sa.String(length=32), nullable=True),
    sa.Column('literary_movement', sa.String(length=128), nullable=True),
    sa.Column('historical_period', sa.String(length=128), nullable=True),
    sa.Column('setting', sa.String(length=255), nullable=True),
    sa.Column('locations', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('long_synopsis', sa.Text(), nullable=True),
    sa.Column('narrative_pov', sa.String(length=128), nullable=True),
    sa.Column('writing_style', sa.String(length=128), nullable=True),
    sa.Column('tone', sa.String(length=128), nullable=True),
    sa.Column('mood', sa.String(length=128), nullable=True),
    sa.Column('pace', sa.String(length=128), nullable=True),
    sa.Column('complexity', sa.String(length=128), nullable=True),
    sa.Column('emotional_intensity', sa.String(length=128), nullable=True),
    sa.Column('main_characters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('character_archetypes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('review_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('awards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bestseller', sa.Boolean(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('embedding_text', sa.Text(), nullable=True),
    sa.Column('search_tsv', sa.Text(), nullable=True),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_canonical_book_confidence'),
    sa.CheckConstraint('rating_count >= 0 AND review_count >= 0', name='ck_canonical_book_counts'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_canonical_book_source_id')
    )
    op.create_index(op.f('ix_canonical_book_language'), 'canonical_book', ['language'], unique=False)
    op.create_index(op.f('ix_canonical_book_source'), 'canonical_book', ['source'], unique=False)
    op.create_index(op.f('ix_canonical_book_source_id'), 'canonical_book', ['source_id'], unique=False)
    op.create_index(op.f('ix_canonical_book_title'), 'canonical_book', ['title'], unique=False)
    op.create_index('ix_canonical_book_updated_at', 'canonical_book', ['updated_at'], unique=False)
    op.create_table('connector_run',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('result_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_run_source'), 'connector_run', ['source'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_email'), 'user_profile', ['email'], unique=True)
    op.create_table('author_identifier_value',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['canonical_author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_identifier_value_identifier'), 'author_identifier_value', ['identifier'], unique=False)
    op.create_table('book_author',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['canonical_author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('book_genre',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['book_category.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.create_table('book_identifier',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('identifier_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_type', 'value', name='uq_book_identifier_type_value')
    )
    op.create_index('ix_book_identifier_book_id', 'book_identifier', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_identifier_identifier_type'), 'book_identifier', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_book_identifier_source'), 'book_identifier', ['source'], unique=False)
    op.create_index(op.f('ix_book_identifier_value'), 'book_identifier', ['value'], unique=False)
    op.create_table('book_subject',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['book_category.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'subject_id')
    )
    op.create_table('book_theme',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['book_category.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'theme_id')
    )
    op.create_table('book_trope',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('trope_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.ForeignKeyConstraint(['trope_id'], ['book_category.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'trope_id')
    )
    op.create_table('canonical_edition',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('isbn10', sa.String(length=32), nullable=True),
    sa.Column('isbn13', sa.String(length=32), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_edition_source'), 'canonical_edition', ['source'], unique=False)
    op.create_index(op.f('ix_canonical_edition_source_id'), 'canonical_edition', ['source_id'], unique=False)
    op.create_table('embedding',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), server_default='local', nullable=False),
    sa.Column('model', sa.String(length=128), server_default='sentence-transformers', nullable=False),
    sa.Column('vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'provider', 'model', name='uq_embedding_book_provider_model')
    )
    op.create_index(op.f('ix_embedding_book_id'), 'embedding', ['book_id'], unique=False)
    op.create_table('ending_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('ending_type', sa.String(length=64), server_default='other', nullable=False),
    sa.Column('bittersweet', sa.Boolean(), nullable=True),
    sa.Column('tragic', sa.Boolean(), nullable=True),
    sa.Column('hopeful', sa.Boolean(), nullable=True),
    sa.Column('open_ended', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ending_metadata_book_id'), 'ending_metadata', ['book_id'], unique=False)
    op.create_table('enrichment_result',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('fields_enriched', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('feed_type', sa.String(length=64), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'feed_type', name='uq_feed_book_type')
    )
    op.create_index(op.f('ix_feed_item_book_id'), 'feed_item', ['book_id'], unique=False)
    op.create_index(op.f('ix_feed_item_feed_type'), 'feed_item', ['feed_type'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1.0 AND rating <= 5.0', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'user_id', name='uq_rating_book_user')
    )
    op.create_index(op.f('ix_rating_book_id'), 'rating', ['book_id'], unique=False)
    op.create_index(op.f('ix_rating_user_id'), 'rating', ['user_id'], unique=False)
    op.create_table('reading_list_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='to_read', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('to_read','reading','finished')", name='ck_reading_status'),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'user_id', name='uq_reading_list_book_user')
    )
    op.create_index(op.f('ix_reading_list_item_book_id'), 'reading_list_item', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_list_item_user_id'), 'reading_list_item', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('review',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('rating_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('spoiler', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(body) <= 20000', name='ck_review_length'),
    sa.ForeignKeyConstraint(['book_id'], ['canonical_book.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'user_id', name='uq_review_book_user')
    )
    op.create_index(op.f('ix_review_book_id'), 'review', ['book_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_book_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_reading_list_item_user_id'), table_name='reading_list_item')
    op.drop_index(op.f('ix_reading_list_item_book_id'), table_name='reading_list_item')
    op.drop_table('reading_list_item')
    op.drop_index(op.f('ix_rating_user_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_book_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_feed_item_feed_type'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_book_id'), table_name='feed_item')
    op.drop_table('feed_item')
    op.drop_table('enrichment_result')
    op.drop_index(op.f('ix_ending_metadata_book_id'), table_name='ending_metadata')
    op.drop_table('ending_metadata')
    op.drop_index(op.f('ix_embedding_book_id'), table_name='embedding')
    op.drop_table('embedding')
    op.drop_index(op.f('ix_canonical_edition_source_id'), table_name='canonical_edition')
    op.drop_index(op.f('ix_canonical_edition_source'), table_name='canonical_edition')
    op.drop_table('canonical_edition')
    op.drop_table('book_trope')
    op.drop_table('book_theme')
    op.drop_table('book_subject')
    op.drop_index(op.f('ix_book_identifier_value'), table_name='book_identifier')
    op.drop_index(op.f('ix_book_identifier_source'), table_name='book_identifier')
    op.drop_index(op.f('ix_book_identifier_identifier_type'), table_name='book_identifier')
    op.drop_index('ix_book_identifier_book_id', table_name='book_identifier')
    op.drop_table('book_identifier')
    op.drop_table('book_genre')
    op.drop_table('book_author')
    op.drop_index(op.f('ix_author_identifier_value_identifier'), table_name='author_identifier_value')
    op.drop_table('author_identifier_value')
    op.drop_index(op.f('ix_user_profile_email'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_connector_run_source'), table_name='connector_run')
    op.drop_table('connector_run')
    op.drop_index('ix_canonical_book_updated_at', table_name='canonical_book')
    op.drop_index(op.f('ix_canonical_book_title'), table_name='canonical_book')
    op.drop_index(op.f('ix_canonical_book_source_id'), table_name='canonical_book')
    op.drop_index(op.f('ix_canonical_book_source'), table_name='canonical_book')
    op.drop_index(op.f('ix_canonical_book_language'), table_name='canonical_book')
    op.drop_table('canonical_book')
    op.drop_index(op.f('ix_canonical_author_source_id'), table_name='canonical_author')
    op.drop_index(op.f('ix_canonical_author_source'), table_name='canonical_author')
    op.drop_table('canonical_author')
    op.drop_index(op.f('ix_book_category_name'), table_name='book_category')
    op.drop_table('book_category')
    # ### end Alembic commands ###
